version: "3.5"
services:
  prometheus:
    build:
      context: ./prometheus
      args:
        UPSTREAM_VERSION: v2.46.0-rc.0
    image: "prometheus.ethical-metrics.dnp.dappnode.eth:0.1.0"
  tor-hidden-service:
    build:
      context: ./tor-hidden-service
    environment:
      EMAIL: null
      REGISTER_URL: "https://ethical-metrics.dappnode.io/targets"
    volumes:
      - "tor-hidden-service:/var/lib/tor/"
    image: "tor-hidden-service.ethical-metrics.dnp.dappnode.eth:0.1.0"
volumes:
  tor-hidden-service: {}
