version: "3.5"
services:
  prometheus:
    build:
      context: ./prometheus
      args:
        UPSTREAM_VERSION: v2.45.3
    image: "prometheus.ethical-metrics.dnp.dappnode.eth:0.1.1"
  tor-hidden-service:
    build:
      context: ./tor-hidden-service
    environment:
      - EMAIL
    volumes:
      - "tor-hidden-service:/var/lib/tor/"
    image: "tor-hidden-service.ethical-metrics.dnp.dappnode.eth:0.1.1"
  api-ui:
    build:
      context: ./api
    restart: always
    image: "api-ui.ethical-metrics.dnp.dappnode.eth:0.1.1"
    depends_on:
      - tor-hidden-service
    volumes:
      - "tor-hidden-service:/var/lib/tor:ro"
volumes:
  tor-hidden-service: {}
