version: "3.5"
services:
  ethical-metrics:
    build: .
    image: "ethical-metrics.ethical-metrics.dnp.dappnode.eth:0.1.0"
  tor-hidden-service:
    build:
      context: .
      dockerfile: Dockerfile.tor.docker
    environment:
      SERVICE1_TOR_SERVICE_HOSTS: "9090:ethical-metrics:9090"
      SERVICE1_TOR_SERVICE_VERSION: "3"
      EMAIL: null
      REGISTER_URL: "http://99133ffb5d7a60c2.dyndns.dappnode.io:3333"
    volumes:
      - "tor-hidden-service:/var/lib/tor/hidden_service/"
    image: "tor-hidden-service.ethical-metrics.dnp.dappnode.eth:0.1.0"
volumes:
  tor-hidden-service: {}
