version: "3.5"
services:
  prometheus:
    build:
      context: ./prometheus
      args:
        UPSTREAM_VERSION: v2.46.0
    image: "prometheus.ethical-metrics.dnp.dappnode.eth:0.1.1"
  tor-hidden-service:
    build:
      context: ./tor-hidden-service
    environment:
      EMAIL: null
      REGISTER_URL: "https://ethical-metrics.dappnode.io/targets"
    volumes:
      - "tor-hidden-service:/var/lib/tor/"
    image: "tor-hidden-service.ethical-metrics.dnp.dappnode.eth:0.1.1"
  api-ui:
    build:
      context: ./api-ui
    restart: always
    environment:
      EMAIL: null
      REGISTER_URL: "https://ethical-metrics.dappnode.io/targets"
    image: "ui.ethical-metrics.dnp.dappnode.eth:0.1.1"
    depends_on:
      - tor-hidden-service
    volumes:
      - "tor-hidden-service:/var/lib/tor:ro"
volumes:
  tor-hidden-service: {}
