version: "3.5"
services:
  prometheus:
    build:
      context: ./prometheus
    image: "prometheus.ethical-metrics.dnp.dappnode.eth:0.1.0"
  tor-hidden-service:
    build:
      context: ./tor-hidden-service
    environment:
      EMAIL: null
      REGISTER_URL: "https://ethical-metrics.dappnode.io/targets"
    volumes:
      - "tor-hidden-service:/var/lib/tor/"
    image: "tor-hidden-service.ethical-metrics.dnp.dappnode.eth:0.1.0"
  ethical-metrics-server:
    build:
      context: ./ethical-metrics-server
    restart: always
    environment:
      EMAIL: null
      REGISTER_URL: "https://ethical-metrics.dappnode.io/targets"
    image: "ethical-metrics-server.ethical-metrics.dnp.dappnode.eth:0.1.0"
    depends_on:
      - tor-hidden-service
    volumes:
      - "tor-hidden-service:/var/lib/tor:ro"
volumes:
  tor-hidden-service: {}
