version: "3.5"
services:
  ethical-metrics:
    build: .
    image: "ethical-metrics.ethical-metrics.dnp.dappnode.eth:0.1.0"
  tor-hidden-service:
    build:
      context: .
      dockerfile: Dockerfile.tor.docker
    environment:
      EMAIL: null
      REGISTER_URL: "https://ethical-metrics.dappnode.io/targets"
    volumes:
      - "tor-hidden-service:/var/lib/tor/"
    image: "tor-hidden-service.ethical-metrics.dnp.dappnode.eth:0.1.0"
volumes:
  tor-hidden-service: {}
