global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      primary: 'ethical-metrics'
scrape_configs:
  - job_name: 'federation'
    scrape_interval: 30s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      - targets:
          - "prometheus.dms.dappnode:9090"
